### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'python'

### ISSUE THREAD

**Issue by zhuyifei1999** [cool-RR/grid_royale#49]
At master (526df2a), on Linux, Python 3.8.7, installed packages:
```
absl-py==0.11.0
astunparse==1.6.3
cachetools==4.2.0
certifi==2020.12.5
chardet==3.0.4
click==7.1.2
Flask==1.1.2
flatbuffers==1.12
gast==0.3.3
google-auth==1.24.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
-e git+https://github.com/cool-RR/grid_royale@526df2a01fa8b0ba39423a6977929539c451673a#egg=grid_royale
grpcio==1.32.0
h5py==2.10.0
idna==2.10
immutabledict==1.2.0
itsdangerous==1.1.0
Jinja2==2.11.2
Keras==2.4.3
Keras-Preprocessing==1.1.2
Markdown==3.3.3
MarkupSafe==1.1.1
more-itertools==8.6.0
numpy==1.19.5
oauthlib==3.1.0
opt-einsum==3.3.0
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyYAML==5.4.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.7
scipy==1.6.0
six==1.15.0
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-estimator==2.4.0
termcolor==1.1.0
typing-extensions==3.7.4.3
urllib3==1.25.11
Werkzeug==1.0.1
wrapt==1.12.1
```

Starting server emits uncaught error:
```
(venv) zhuyifei1999@zhuyifei1999-ThinkPad-T480 /tmp/grid_royale $ grid_royale play
Traceback (most recent call last):
  File "/tmp/grid_royale/venv/bin/grid_royale", line 33, in <module>
    sys.exit(load_entry_point('grid-royale', 'console_scripts', 'grid_royale')())
  File "/tmp/grid_royale/venv/bin/grid_royale", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/grid_royale/grid_royale/__init__.py", line 9, in <module>
    from .base import *
  File "/tmp/grid_royale/grid_royale/base.py", line 74, in <module>
    from . import utils
  File "/tmp/grid_royale/grid_royale/utils/__init__.py", line 53, in <module>
    copyreg.pickle(tensorflow.python._tf_stack.StackSummary, pickle_stack_summary)
AttributeError: module 'tensorflow' has no attribute 'python'
```

**Comment by cool-RR** [comment]
Thanks for finding this! I believe I fixed it now.
